<a href="https://colab.research.google.com/github/swarupyeole11/ML_Journey/blob/main/Pandas_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [6]:

#the sereis datatype has index and dtype mentoned
my_data = ['boot','car','bike','truck']
my_series = pd.Series(my_data)
print(my_series)

my_data = ['boot','car','bike','truck',23]
my_series = pd.Series(my_data)
print(my_series)


0     boot
1      car
2     bike
3    truck
dtype: object
0     boot
1      car
2     bike
3    truck
4       23
dtype: object


#Dataframe 

dataframe is the grouping of multiple series all linked by same index

In [10]:
mydfdata = [('Boat',1),('car',55),('Bike',99)]
df = pd.DataFrame(mydfdata)
print(df)

#you can access the data frame like arrays
print(df[0][1])



      0   1
0  Boat   1
1   car  55
2  Bike  99
car


In [14]:
mydfdata = [('Boat',1),('car',55),('Bike',99)]

#giving names to the columns
df = pd.DataFrame(mydfdata,columns=['vehicle','count'])
print(df)

#just to show that the dataframes are just collection of serties pritning the dataype of one of the column
print(type(df['vehicle']))



  vehicle  count
0    Boat      1
1     car     55
2    Bike     99
<class 'pandas.core.series.Series'>


In [16]:
# to see dtypes of all columns
df.dtypes


vehicle    object
count       int64
dtype: object

In [18]:
# to see all the columns in the data frame 
df.columns


Index(['vehicle', 'count'], dtype='object')

In [19]:
#there is no attribute called rows 
df.rows

AttributeError: ignored

#Reading the data

In [20]:
df = pd.read_csv('/content/drive/MyDrive/Predictive/snsdata.csv')

#Analyzing the data

In [21]:
df.columns

Index(['gradyear', 'gender', 'age', 'friends', 'basketball', 'football',
       'soccer', 'softball', 'volleyball', 'swimming', 'cheerleading',
       'baseball', 'tennis', 'sports', 'cute', 'sex', 'sexy', 'hot', 'kissed',
       'dance', 'band', 'marching', 'music', 'rock', 'god', 'church', 'jesus',
       'bible', 'hair', 'dress', 'blonde', 'mall', 'shopping', 'clothes',
       'hollister', 'abercrombie', 'die', 'death', 'drunk', 'drugs'],
      dtype='object')

In [23]:
#gives basic staistics of the data
df.describe()

gradyear           age       friends    basketball      football  \
count  30000.000000  24914.000000  30000.000000  30000.000000  30000.000000   
mean    2007.500000     17.993950     30.179467      0.267333      0.252300   
std        1.118053      7.858054     36.530877      0.804708      0.705357   
min     2006.000000      3.086000      0.000000      0.000000      0.000000   
25%     2006.750000     16.312000      3.000000      0.000000      0.000000   
50%     2007.500000     17.287000     20.000000      0.000000      0.000000   
75%     2008.250000     18.259000     44.000000      0.000000      0.000000   
max     2009.000000    106.927000    830.000000     24.000000     15.000000   

             soccer      softball    volleyball     swimming  cheerleading  \
count  30000.000000  30000.000000  30000.000000  30000.00000  30000.000000   
mean       0.222767      0.161200      0.143133      0.13440      0.106633   
std        0.917226      0.739707      0.639943      0.51699      0.514333   
min        0.000000      0.000000      0.000000      0.00000      0.000000   
25%        0.000000      0.000000      0.000000      0.00000      0.000000   
50%        0.000000      0.000000      0.000000      0.00000      0.000000   
75%        0.000000      0.000000      0.000000      0.00000      0.000000   
max       27.000000     17.000000     14.000000     31.00000      9.000000   

       ...        blonde          mall      shopping      clothes  \
count  ...  30000.000000  30000.000000  30000.000000  30000.00000   
mean   ...      0.098933      0.257367      0.353000      0.14850   
std    ...      1.942319      0.695758      0.724391      0.47264   
min    ...      0.000000      0.000000      0.000000      0.00000   
25%    ...      0.000000      0.000000      0.000000      0.00000   
50%    ...      0.000000      0.000000      0.000000      0.00000   
75%    ...      0.000000      0.000000      1.000000      0.00000   
max    ...    327.000000     12.000000     11.000000      8.00000   

          hollister   abercrombie           die         death         drunk  \
count  30000.000000  30000.000000  30000.000000  30000.000000  30000.000000   
mean       0.069867      0.051167      0.184100      0.114233      0.087967   
std        0.346779      0.279555      0.624516      0.436796      0.399125   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      0.000000      0.000000      0.000000      0.000000   
50%        0.000000      0.000000      0.000000      0.000000      0.000000   
75%        0.000000      0.000000      0.000000      0.000000      0.000000   
max        9.000000      8.000000     22.000000     14.000000      8.000000   

              drugs  
count  30000.000000  
mean       0.060433  
std        0.345522  
min        0.000000  
25%        0.000000  
50%        0.000000  
75%        0.000000  
max       16.000000  

[8 rows x 39 columns]

In [24]:
df.head()

gradyear gender     age  friends  basketball  football  soccer  softball  \
0      2006      M  18.982        7           0         0       0         0   
1      2006      F  18.801        0           0         1       0         0   
2      2006      M  18.335       69           0         1       0         0   
3      2006      F  18.875        0           0         0       0         0   
4      2006    NaN  18.995       10           0         0       0         0   

   volleyball  swimming  ...  blonde  mall  shopping  clothes  hollister  \
0           0         0  ...       0     0         0        0          0   
1           0         0  ...       0     1         0        0          0   
2           0         0  ...       0     0         0        0          0   
3           0         0  ...       0     0         0        0          0   
4           0         0  ...       0     0         2        0          0   

   abercrombie  die  death  drunk  drugs  
0            0    0      0      0      0  
1            0    0      0      0      0  
2            0    0      1      0      0  
3            0    0      0      0      0  
4            0    0      0      1      1  

[5 rows x 40 columns]

In [30]:
# Checking the data types of each column present
df.dtypes


gradyear          int64
gender           object
age             float64
friends           int64
basketball        int64
football          int64
soccer            int64
softball          int64
volleyball        int64
swimming          int64
cheerleading      int64
baseball          int64
tennis            int64
sports            int64
cute              int64
sex               int64
sexy              int64
hot               int64
kissed            int64
dance             int64
band              int64
marching          int64
music             int64
rock              int64
god               int64
church            int64
jesus             int64
bible             int64
hair              int64
dress             int64
blonde            int64
mall              int64
shopping          int64
clothes           int64
hollister         int64
abercrombie       int64
die               int64
death             int64
drunk             int64
drugs             int64
dtype: object

In [31]:
df.count

<bound method DataFrame.count of        gradyear gender     age  friends  basketball  football  soccer  \
0          2006      M  18.982        7           0         0       0   
1          2006      F  18.801        0           0         1       0   
2          2006      M  18.335       69           0         1       0   
3          2006      F  18.875        0           0         0       0   
4          2006    NaN  18.995       10           0         0       0   
...         ...    ...     ...      ...         ...       ...     ...   
29995      2009      M  16.115        0           0         0       0   
29996      2009      M  15.792        1           0         1       0   
29997      2009      M  15.784        0           0         1       0   
29998      2009      M  16.378        0           0         0       0   
29999      2009      F  18.724        3           2         0       0   

       softball  volleyball  swimming  ...  blonde  mall  shopping  clothes  \
0          

#columns and rows 

In [71]:
#looking for specific column 
print(df['gender'])

#to know the numeer of rows and columns in the dataframe
print(df.shape)

0          M
1          F
2          M
3          F
4        NaN
        ... 
29995      M
29996      M
29997      M
29998      M
29999      F
Name: gender, Length: 30000, dtype: object
(30000, 40)


In [35]:
#looking for specific row
print(df.loc[2:4])



   gradyear gender     age  friends  basketball  football  soccer  softball  \
2      2006      M  18.335       69           0         1       0         0   
3      2006      F  18.875        0           0         0       0         0   
4      2006    NaN  18.995       10           0         0       0         0   

   volleyball  swimming  ...  blonde  mall  shopping  clothes  hollister  \
2           0         0  ...       0     0         0        0          0   
3           0         0  ...       0     0         0        0          0   
4           0         0  ...       0     0         2        0          0   

   abercrombie  die  death  drunk  drugs  
2            0    0      1      0      0  
3            0    0      0      0      0  
4            0    0      0      1      1  

[3 rows x 40 columns]


In [37]:
#looking for specific row with specified number of columns
df.loc[2:4,['age','friends']]


age  friends
2  18.335       69
3  18.875        0
4  18.995       10

## The Set Index is useful when working with timeseries data where we manipulate data by the timestamp

In [53]:
#to set the row index to a specific value you can use the setindex function
df.set_index('gender')

#to premenately modify the dataframe you will have to use
# df = df.set_index('gender)

gradyear     age  friends  basketball  football  soccer  softball  \
gender                                                                      
M           2006  18.982        7           0         0       0         0   
F           2006  18.801        0           0         1       0         0   
M           2006  18.335       69           0         1       0         0   
F           2006  18.875        0           0         0       0         0   
NaN         2006  18.995       10           0         0       0         0   
...          ...     ...      ...         ...       ...     ...       ...   
M           2009  16.115        0           0         0       0         0   
M           2009  15.792        1           0         1       0         0   
M           2009  15.784        0           0         1       0         0   
M           2009  16.378        0           0         0       0         0   
F           2009  18.724        3           2         0       0         1   

        volleyball  swimming  cheerleading  ...  blonde  mall  shopping  \
gender                                      ...                           
M                0         0             0  ...       0     0         0   
F                0         0             0  ...       0     1         0   
M                0         0             0  ...       0     0         0   
F                0         0             0  ...       0     0         0   
NaN              0         0             0  ...       0     0         2   
...            ...       ...           ...  ...     ...   ...       ...   
M                0         0             0  ...       0     0         0   
M                0         0             0  ...       0     0         0   
M                0         0             0  ...       0     0         0   
M                0         0             0  ...       0     0         0   
F                0         0             0  ...       0     0         0   

        clothes  hollister  abercrombie  die  death  drunk  drugs  
gender                                                             
M             0          0            0    0      0      0      0  
F             0          0            0    0      0      0      0  
M             0          0            0    0      1      0      0  
F             0          0            0    0      0      0      0  
NaN           0          0            0    0      0      1      1  
...         ...        ...          ...  ...    ...    ...    ...  
M             0          0            0    0      0      0      0  
M             0          0            0    0      0      0      0  
M             0          0            0    0      0      0      0  
M             0          0            0    0      0      0      0  
F             0          0            0    0      0      0      0  

[30000 rows x 39 columns]

In [42]:
df['gender'].unique()  #to get all the unique values present in that column

array(['M', 'F', nan], dtype=object)

In [51]:
x = df['age'].unique()
print(type(x))

#this shape indica
x.shape

(2215,)

No, the shapes (2215,) and (2215,1) are not the same in numpy array.

The shape (2215,) indicates a 1-dimensional numpy array with 2215 elements. This is sometimes called a "flat" array or a "vector". Each element in the array can be accessed with a single index.

On the other hand, the shape (2215,1) indicates a 2-dimensional numpy array with 2215 rows and 1 column. This is sometimes called a "column vector". Each element in the array requires two indices to access, one for the row and one for the column.

Even though both shapes have the same number of elements, they represent different types of data structures and may require different approaches for certain operations in numpy.

In [64]:
#converting 1 D numpy array into 2D numpy array
x_new = x.reshape(2215,1)
print(x_new.shape)

#the same can be achieved using this code
x_new_alpha = x.reshape(-1,1)
# it tells the python to make sure that the data had 1 column and adjust he number of rows for the data accordingly


(2215, 1)


In [70]:
# converting a 2d array in to 3d array
x_3d = x.reshape(1,5,-1)  #make sure when you reshape an array the new dimesions when multpied are equal to the old ones when multpled for e.g     1*2215 = 1*5*443
print(x_3d.shape)
print(x_3d)

(1, 5, 443)
[[[ 18.982  18.801  18.335 ...  18.371  18.79   18.702]
  [ 19.305  18.22   17.982 ...  20.611  17.407  20.033]
  [ 17.394  27.387   5.451 ...  37.645  37.407  14.275]
  [ 64.63   17.068  46.919 ... 106.817  15.546  23.255]
  [106.842 105.955   5.572 ...  14.94   37.136  33.194]]]
